[ option.doctype ]
  show          = true

[output]
  fileext       = 'html'

[output.program]
  pdf           = 'wkhtmltopdf - %of.pdf'
#  fmt           = 'xmllint --format --noent - > %of.%oe'
#  tidy          = 'tidy --output-html 1 - >%of.%oe'

[module]
  report        = 'SxmlLib::Testing::Report'
  code          = 'SxmlLib::Testing::Code'
  test          = 'SxmlLib::Testing::Test'
  todo          = 'SxmlLib::Testing::Todo'
  bug           = 'SxmlLib::Testing::Bug'
  skip          = 'SxmlLib::Testing::Skip'
  lorem         = 'SxmlLib::LoremIpsum'
