[option.doctype]
  show          = 0

[output]
  fileext       = 'html'

[output.program]
  pdf           = 'wkhtmltopdf - %of.pdf'

[module]
  report        = 'SxmlLib::Testing::Report'
  test          = 'SxmlLib::Testing::Test'
  code          = 'SxmlLib::Testing::Code'
