branches:
  only:
    - master
    - develop

language: perl6

perl6:
#  - latest
  - '2017.02'

install:
#  - rakudobrew build-zef ${TRAVIS_PERL6_VERSION#latest}
  - rakudobrew build-zef 2017.02
#  - zef update
#  - zef --/test install Config::DataLang::Refine
#  - zef --/test install https://github.com/MARTIMM/config-datalang-refine.git
#  - zef install XML
#  - zef install Terminal::ANSIColor

#  - zef --depsonly install .
  - zef --/test --depsonly install .

cache:
  directories:
#    - $TRAVIS_BUILD_DIR/.rakudobrew
    - $HOME/Travis-ci
    - $HOME/.rakudobrew
