branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - rakudobrew build-panda ${TRAVIS_PERL6_VERSION#latest}
#  - panda installdeps .
  - panda update
  - panda --notests install XML
  - panda --notests Config::DataLang::Refine
  - panda --notests Terminal::ANSIColor

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.rakudobrew
