[ general ]
  title        = 'Basic SemiXML tests'
  package      = '-'
  module       = '-'
  class        = '-'
  distribution = '-'
  label        = '-'
  date         = '2018-02-18T20:17:13.707930Z'
  oskernel     = 'linux:4.14.18.200.fc.26.x.86._.64'
  osdistro     = 'fedora:26.Workstation.Edition:26:False'
  perl         = 'Perl 6:6.c'
  compiler     = 'rakudo:2018.01.195.g.5.ae.1.ca.51.f'
  vm           = 'moar:2018.01.89.ga.01.cdb.449'

[ purpose ]
  purposetitle = 'Testing the basic use of SemiXML'
  purpose      = '''
$p title="purpose"  [

    Purpose of this report is that it tests the parsing and translating process
    of the several parts of the language. Here only the simple structures are
    tested and not the methods to generate new content.
  
  $p  [
  The tests comprises the following chapters
  ]
  $ul  [
    $li  [
    Generate a simple element
    ]
  ]
]

'''

[ chapters ]
  list         = [ 'Generate a simple element' ]
  success      = 2
  fail         = 0
  todo         = 0
  skipped      = 0

[ summary.line-7 ]
  chapter      = ''
  diagnostic   = """
    ok 1 - The object is-a 'SemiXML::Sxml'
"""

[ summary.line-10 ]
  chapter      = ''
  diagnostic   = """
    ok
"""
