[option.doctype]
  show          = 0

[output]
  fileext       = 'html'

[output.program]
  pdf           = 'wkhtmltopdf - %op/%of.pdf'
  xml           = 'cat > %op/%of.xml'

[module]
  lorem         = 'SxmlLib::LoremIpsum'
  file          = 'SxmlLib::File'

