#------------------------------------------------------------------------------
# Content additions tables
[ C ]
  xml-show          = false
  doctype-show      = false
  header-show       = false

[ C.xml ]
  xml-show          = true

[ C.html ]
  doctype-show      = true

#------------------------------------------------------------------------------
# Dependency tables
#[ D.html ]
#  pdf = [ 'xml; html; table1.xml', 'xml; html; table2.xml']

#------------------------------------------------------------------------------
# Doctype entity tables
#[ E.xml ]
#  copy              = '&#xa9;'

#------------------------------------------------------------------------------
[ F.html ]
  inline            = [
    'a', 'b', 'big', 'i', 'strong', 'small', 'tt', 'abbr', 'acronym', 'cite',
    'code', 'dfn', 'em', 'kbd', 'strong', 'samp', 'time', 'var', 'bdo', 'br',
    'img', 'map', 'object', 'q', 'script', 'span', 'sub', 'sup', 'button',
    'input', 'label', 'select', 'textarea'
  ]

#  non-nesting       = [ 'code', 'script', 'style', 'tt', 'kbd']
  no-escaping       = [ 'style', 'script']
  space-preserve    = [ 'pre' ]
  self-closing      = [
    'area', 'base', 'br', 'col', 'command', 'embed', 'hr', 'img', 'input',
    'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr'
  ]


[ F.db5 ]
  inline            = [
    'emphasis'
  ]

  no-escaping       = [

  ]

  space-preserve    = [
    'programlisting'
  ]

  self-closing      = [

  ]

#------------------------------------------------------------------------------
# Header table
[ H.html ]
  Content-Type          = 'text/html; charset="utf-8"'
#  From                  = 'my-addr@gmail.com'
#  User-Agent            = 'SemiXML'
#  Content-Style-Type    = 'text/css'

#------------------------------------------------------------------------------
# Module and library path tables
[ ML ]
#  label           = 'module[;path to module]'
  SxmlCore        = 'SxmlLib::SxmlCore'

#------------------------------------------------------------------------------
# Running programs tables
[ R ]
  cat             = 'cat > "%op/%of.%oe"'

[ R.xml ]
  fmt             = 'xmllint --format - > "%op/%of.%oe"'
#  fmt             = 'xmllint --format --noent - > %op/%of.%oe'
#  pdf             = 'wkhtmltopdf - %op/%of.pdf'
#  chk             = [ 'tidy -xml > tidy.html', 'tidy.html']
#  other           = ['cat > backup.xml', 'backup.xml']

#------------------------------------------------------------------------------
# Storage tables
# [ S.* ]
#   rootpath
#   filepath
#   fileext
[ S ]
  fileext       = 'xml'

[S.html]
  fileext       = 'html'

[S.xhtml]
  fileext       = 'xhtml'

[S.pdf]
  fileext       = 'pdf'

[S.svg]
  fileext       = 'svg'

[ S.xsl ]
  fileext       = 'xsl'

#------------------------------------------------------------------------------
# Tracing tables
[ T ]
  config        = false
  tables        = false
  modules       = false
  parse         = false
  parse-result  = false
  file-handling = true

#------------------------------------------------------------------------------
# XML description tables
[ X ]
  xml-version     = '1.0'
  xml-encoding    = 'UTF-8'

  # Default for xml is 'no'. Is only relevant when a DTD is used.
#  xml-standalone  = 'no'
