#-------------------------------------------------------------------------------
# Content additions tables. Refined using OUT and basename.
[ C ]
  xml-show          = false
  doctype-show      = false
  header-show       = false

[ C.xml ]
  xml-show          = true

[ C.html ]
  doctype-show      = true

#-------------------------------------------------------------------------------
# Dependency tables. Refined using IN and basename.
#[ D.html ]
#  pdf = [ 'xml; html; table1.xml', 'xml; html; table2.xml']

#-------------------------------------------------------------------------------
# Default namespaces table. Refined using IN and basename.
#  xi      = 'http://www.w3.org/2001/XInclude'
#  xlink   = 'http://www.w3.org/1999/xlink'
#  xml     = "http://www.w3.org/XML/1998/namespace"

#[ DN ]
#  sxml = "https://github.com/MARTIMM/Semi-xml"

[ DN.html ]
  default = "http://www.w3.org/1999/xhtml"

[ DN.db5 ]
  default = "http://docbook.org/ns/docbook"

#-------------------------------------------------------------------------------
# Doctype entity tables. Refined using IN and basename.
#[ E.xml ]
#  copy              = '&#xa9;'

#-------------------------------------------------------------------------------
# Element handling tables. Refined using IN and basename.
[ F ]
  # modules and methods
  inline            = [
    'sxml:SxmlCore.date', 'sxml:SxmlCore.date-time',
    'sxml:comment', 'sxml:cdata', 'sxml:xml'
  ]

  space-preserve    = [ 'sxml:cdata', 'sxml:pi', 'sxml:xml' ]
  no-conversion     = [ 'sxml:cdata', 'sxml:pi', 'sxml:xml' ]


[ F.html ]
  inline            = [
    'a', 'b', 'big', 'i', 'strong', 'small', 'tt', 'abbr', 'acronym', 'cite',
    'code', 'dfn', 'em', 'kbd', 'strong', 'samp', 'time', 'var', 'bdo', 'br',
    'img', 'map', 'object', 'q', 'script', 'span', 'sub', 'sup', 'button',
    'input', 'label', 'select', 'textarea'
  ]

#  non-nesting       = [ 'code', 'script', 'style', 'tt', 'kbd']
  no-conversion     = [ 'style', 'script']
  space-preserve    = [ 'pre' ]
  self-closing      = [
    'area', 'base', 'br', 'col', 'command', 'embed', 'hr', 'img', 'input',
    'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr'
  ]


# Docbook 5
[ F.db5 ]
  # From https://tdg.docbook.org/tdg/5.1/ch02.html, 3.8. Content model patterns
  # There are several repetitions of elements
  inline            = [
    # Bibliography inlines
    'citation', 'citerefentry', 'citetitle', 'citebiblioid', 'author', 'person', 'personname', 'org', 'orgname', 'editor', 'jobtitle',

    # Computer-output inlines
    'inlinemediaobject', 'remark', 'xref', 'link', 'olink', 'anchor', 'biblioref', 'alt', 'trademark', 'abbrev', 'acronym', 'date', 'emphasis', 'footnote', 'footnoteref', 'foreignphrase', 'phrase', 'quote', 'subscript', 'superscript', 'wordasword', 'annotation', 'firstterm', 'glossterm', 'indexterm', 'coref', 'prompt', 'envar', 'filename', 'command', 'computeroutput', 'userinput', 'replaceable', 'package', 'parameter', 'termdef', 'nonterminal', 'systemitem', 'option', 'optional', 'property', 'co', 'tag', 'markup', 'token', 'symbol', 'literal', 'code', 'constant', 'email', 'uri',

    # Error inlines
    'errorcode', 'errortext', 'errorname', 'errortype',

    # Graphic inlines
    'inlinemediaobject',

    # GUI inlines
    'guiicon', 'guibutton', 'guimenuitem', 'guimenu', 'guisubmenu', 'guilabel', 'menuchoice', 'mousebutton',

    # Indexing inlines
    'indexterm',

    # Keyboard inlines
    'keycombo', 'keycap', 'keycode', 'keysym', 'shortcut', 'accel',

    # Linking inlines
    'xref', 'link', 'olink', 'anchor', 'biblioref',

    # Markup inlines
    'tag', 'markup', 'token', 'symbol', 'literal', 'code', 'constant', 'email', 'uri',

    # Math inlines
    'inlineequation',

    # Object-oriented programming inlines
    'ooclass', 'ooexception', 'oointerface',

    # Operating system inlines
    'prompt', 'envar', 'filename', 'command', 'computeroutput', 'userinput',

    # Product inlines
    'trademark', 'productnumber', 'productname', 'database', 'application', 'hardware',

    # Programming inlines
    'function', 'parameter', 'varname', 'returnvalue', 'type', 'classname', 'exceptionname', 'interfacename', 'methodname', 'modifier', 'initializer', 'ooclass', 'ooexception', 'oointerface',

    # Publishing inlines
    'abbrev', 'acronym', 'date', 'emphasis', 'footnote', 'footnoteref', 'foreignphrase', 'phrase', 'quote', 'subscript', 'superscript', 'wordasword', 'firstterm', 'glossterm', 'coref',

    # Technical inlines
    'replaceable', 'package', 'parameter', 'termdef', 'nonterminal', 'systemitem', 'option', 'optional', 'property',

    # Ubiquitous inlines
    'inlinemediaobject', 'remark', 'xref', 'link', 'olink', 'anchor', 'biblioref', 'alt', 'trademark', 'abbrev', 'acronym', 'date', 'emphasis', 'footnote', 'footnoteref', 'foreignphrase', 'phrase', 'quote', 'subscript', 'superscript', 'wordasword', 'annotation', 'firstterm', 'glossterm', 'indexterm', 'coref',

    # User-input inlines
    'inlinemediaobject', 'remark', 'xref', 'link', 'olink', 'anchor', 'biblioref', 'alt', 'trademark', 'abbrev', 'acronym', 'date', 'emphasis', 'footnote', 'footnoteref', 'foreignphrase', 'phrase', 'quote', 'subscript', 'superscript', 'wordasword', 'annotation', 'firstterm', 'glossterm', 'indexterm', 'coref', 'prompt', 'envar', 'filename', 'command', 'computeroutput', 'userinput', 'replaceable', 'package', 'parameter', 'termdef', 'nonterminal', 'systemitem', 'option', 'optional', 'property', 'co', 'tag', 'markup', 'token', 'symbol', 'literal', 'code', 'constant', 'email', 'uri', 'guiicon', 'guibutton', 'guimenuitem', 'guimenu', 'guisubmenu', 'guilabel', 'menuchoice', 'mousebutton', 'keycombo', 'keycap', 'keycode', 'keysym', 'shortcut', 'accel'
  ]

  no-conversion       = [

  ]

  space-preserve    = [
    # Verbatim elements
    'screen', 'literallayout', 'programlistingco', 'screenco', 'programlisting', 'synopsis'
  ]

  self-closing      = [

  ]

#-------------------------------------------------------------------------------
# Header table. Refined using OUT and basename.
[ H.html ]
  Content-Type          = 'text/html; charset="utf-8"'
#  From                  = 'my-addr@gmail.com'
#  User-Agent            = 'SemiXML'
#  Content-Style-Type    = 'text/css'

#-------------------------------------------------------------------------------
# Module and library path tables. Refined using IN and basename.
#  label           = 'module[;path to module]'
[ ML ]

#  core            = 'SxmlLib::SxmlCore'
#  css             = 'SxmlLib::Html::Css'
#  core            = 'SxmlLib::SxmlCore'
  SxmlCore        = 'SxmlLib::SxmlCore'

#-------------------------------------------------------------------------------
# Running programs tables. Refined using IN and basename. The keys are
# selected by OUT.
[ R ]
  cat             = 'cat > "%op/%of.%oe"'

[ R.xml ]
  fmt             = 'xmllint --format - > "%op/%of.%oe"'
#  fmt             = 'xmllint --format --noent - > %op/%of.%oe'
#  pdf             = 'wkhtmltopdf - %op/%of.pdf'
#  chk             = [ 'tidy -xml > tidy.html', 'tidy.html']
#  other           = ['cat > backup.xml', 'backup.xml']

#-------------------------------------------------------------------------------
# Storage tables. Refined using OUT and basename.
# [ S.* ]
#   rootpath
#   filepath
#   fileext
[ S ]
  fileext       = 'xml'

[S.html]
  fileext       = 'html'

[S.xhtml]
  fileext       = 'xhtml'

[S.pdf]
  fileext       = 'pdf'

[S.svg]
  fileext       = 'svg'

[ S.xsl ]
  fileext       = 'xsl'

#-------------------------------------------------------------------------------
# Tracing tables. Refined using basename.
[ T ]
  config        = false
  tables        = false
  modules       = false
  parse         = false
  parse-result  = false
  file-handling = true

#-------------------------------------------------------------------------------
# User definitions to be used by modules. Refined using IN, OUT and basename.
[ U ]

#-------------------------------------------------------------------------------
# XML description tables. Refined using OUT and basename.
[ X ]
  xml-version     = '1.0'
  xml-encoding    = 'UTF-8'

  # Default for xml is 'no'. Is only relevant when a DTD is used.
#  xml-standalone  = 'no'
