#[ dependencies ]
#  file          = [ ]

#[ module ]

#[ option ]

[ option.http-header ]
  show          = false

[ option.xml-prelude ]
  show          = false
  version       = '1.0'
  encoding      = 'UTF-8'

[ option.doctype ]
  show          = false

#[ option.doctype.entities ]
#  copy          = '&#xa9;'


[ output ]
  fileext       = 'xml'

[ output.program ]
#  fmt           = 'xmllint --format --noent - > %of.%oe'
#  pdf           = 'wkhtmltopdf - %of.pdf'
#  chk           = 'tidy -'


#TODO [ styles ]
