#[ dependencies ]
#  file          = [ ]

[ module ]
  SxmlCore      = 'SxmlLib::SxmlCore'

#[ option ]

[ option.http-header ]
  show          = false

[ option.xml-prelude ]
  show          = false
  version       = '1.0'
  encoding      = 'UTF-8'
#  standalone    = 'yes'

[ option.doctype ]
  show          = false

#[ option.doctype.entities ]
#  copy          = '&#xa9;'


[ output ]
  fileext       = 'xml'

[ output.program ]
#  pdf           = 'wkhtmltopdf - %op/%of.pdf'
#  fmt           = 'xmllint --format --noent - > %op/%of.%oe'
#  chk           = 'tidy -'


#TODO [ styles ]
