[ dependencies ]
#  file          = [ ]

#[ module ]

#[ option ]

[ option.doctype ]
  show          = false

#[ option.doctype.entities ]

[ option.http-header ]
  show          = false

[ option.xml-prelude ]
  show          = false
  version       = '1.0'
  encoding      = 'UTF-8'


[ output ]
  fileext       = 'xml'

#[ output.program ]
#  c1 = 'wkhtml2pdf - %f'


#TODO [ styles ]
