#[ dependencies ]
#  file          = [ ]

[ module ]
  SxmlCore      = 'SxmlLib::SxmlCore'

#[ option ]

[ option.http-header ]
  show          = false

[ option.xml-prelude ]
  show          = false
  version       = '1.0'
  encoding      = 'UTF-8'
#  standalone    = 'yes'

[ option.doctype ]
  show          = false

#[ option.doctype.entities ]
#  copy          = '&#xa9;'


[ output ]
  fileext       = 'xml'

[ output.program ]
#  pdf           = 'wkhtmltopdf - %op/%of.pdf'
#  fmt           = 'xmllint --format --noent - > %op/%of.%oe'
#  chk           = 'tidy -'


# New style of configuration tables
[ C ]
  xml-show      = false
  version       = '1.0'
  encoding      = 'UTF-8'
  standalone    = 'yes'

  doctype-show  = false
  http-show     = false

#[ D ]
#  file          = [ ]

#[ E ]
#  copy          = '&#xa9;'

# if [ H ] has entries, show http header
#[ H ]

[ ML ]
  SxmlCore      = 'SxmlLib::SxmlCore'

[ R ]
  fmt           = 'xmllint --format - > %op/%of.%oe'
#  fmt           = 'xmllint --format --noent - > %op/%of.%oe'
#  pdf           = 'wkhtmltopdf - %op/%of.pdf'
#  chk           = 'tidy -'

[ S ]
  fileext       = 'xml'
