#------------------------------------------------------------------------------
# Content definition tables
[ C ]
  xml-show        = false
  xml-version     = '1.0'
  xml-encoding    = 'UTF-8'
#  xml-standalone  = 'yes'

  doctype-show    = false
  header-show     = false

[ C.xml ]
  xml-show        = true

[ C.html ]
  doctype-show    = true

  inline          = [
    'a', 'b', 'big', 'i', 'strong', 'small', 'tt', 'abbr', 'acronym', 'cite',
    'code', 'dfn', 'em', 'kbd', 'strong', 'samp', 'time', 'var', 'bdo', 'br',
    'img', 'map', 'object', 'q', 'script', 'span', 'sub', 'sup', 'button',
    'input', 'label', 'select', 'textarea'
  ]

  non-nesting     = [ 'code', 'script', 'style', 'tt', 'kbd']
  space-preserve  = [ 'pre' ]

#------------------------------------------------------------------------------
# Dependency tables
#[ D ]
#  files           = [ ]

#------------------------------------------------------------------------------
# Doctype entity tables
[ E.xml ]
  copy            = '&#xa9;'

#------------------------------------------------------------------------------
# Header table
#[ H ]
#  Content-Type    = 'text/html; charset="utf-8"'
#  From            = 'my-addr@gmail.com'
#  User-Agent      = 'SemiXML'

#------------------------------------------------------------------------------
# Module and library path tables
[ ML ]
  SxmlCore      = 'SxmlLib::SxmlCore'

#------------------------------------------------------------------------------
# Running programs tables
[ R ]
  fmt           = 'xmllint --format - > %op/%of.%oe'
#  fmt           = 'xmllint --format --noent - > %op/%of.%oe'
#  pdf           = 'wkhtmltopdf - %op/%of.pdf'
#  chk           = 'tidy -'

#------------------------------------------------------------------------------
# Storage tables
[ S ]
  fileext       = 'xml'
