#------------------------------------------------------------------------------
[C]
  tracing       = true

#------------------------------------------------------------------------------
[ML]
  lorem         = 'SxmlLib::LoremIpsum'

#------------------------------------------------------------------------------
[R.html]
  pdf           = 'wkhtmltopdf - %op/%of.%oe'
  xml           = 'xmllint --format - > %op/%of.%oe'

#------------------------------------------------------------------------------
[ T ]
#  config-search = false
  config        = false
  tables        = false
  modules       = false
  parse         = false
  parse-result  = false
  file-handling = true
