[ general ]
  title        = 'Basic SemiXML tests'
  package      = '-'
  module       = '-'
  class        = '-'
  distribution = '-'
  label        = '-'
  date         = '2017-12-21T19:02:09.421154Z'
  oskernel     = 'linux:4.14.4.200.fc.26.x.86._.64'
  osdistro     = 'fedora:26.Workstation.Edition:26:False'
  perl         = 'Perl 6:6.c'
  compiler     = 'rakudo:2017.11.121.gfb.8.ea.2248'
  vm           = 'moar:2017.11.43.g.93.a.77.dc.1'

[ chapter.c1 ]
  name         = 'Test SemiXML::Sxml object and simple input'
  success      = 2
  fail         = 1
  todo         = 0
  skipped      = 0

[ chapter.c2 ]
  name         = 'jklzflkjhflkja fd'
  success      = 2
  fail         = 2
  todo         = 1
  skipped      = 0

[ summary.line-7 ]
  chapter      = 'Test SemiXML::Sxml object and simple input'
  diagnostic   = """
    ok 1 - The object is-a 'SemiXML::Sxml'
"""

[ summary.line-12 ]
  chapter      = 'Test SemiXML::Sxml object and simple input'
  diagnostic   = """
    ok 2 - The generated xml is conforming the standard
"""

[ summary.line-15 ]
  chapter      = 'Test SemiXML::Sxml object and simple input'
  diagnostic   = """
    not ok 3 - uhmm...
    Failed test 'uhmm...'
    at xt/Sxml/001-basic2.t line 15
    expected: '3'
    got: '2'
"""

[ summary.line-16 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 4 - jhg djhgasd asjh
    Looks like you planned 7 tests, but ran 4
    Looks like you failed 2 tests of 4
    Failed test 'jhg djhgasd asjh'
    at xt/Sxml/001-basic2.t line 16
"""

[ summary.line-19 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    ok 1 - yes one is one
"""

[ summary.line-20 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    ok 2 - and two is two
"""

[ summary.line-21 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 3 - and two is not three
    Failed test 'and two is not three'
    at xt/Sxml/001-basic2.t line 21
    expected: '3'
    got: '2'
"""

[ summary.line-23 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 4 - return a failure
    Failed test 'right exception type (Str)'
    at /home/marcel/Software/perl6/rakudo/install/share/perl6/precomp/DC5BE813D5C4C72C72FC6AF6489772C18342AD3B.1513266865.70398/C7/C712FE6969F786C9380D643DF17E85D06868219E line 1
    Expected: Str
    Got:      X::AdHoc
    Exception message: awkward
    Looks like you failed 1 test of 3
    Failed test 'return a failure'
    at xt/Sxml/001-basic2.t line 23
"""

[ summary.line-27 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 5 - jhgj jh jh jhg # TODO working on it
"""

[ summary.line-28 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 1 - not yet, maybe later # TODO working on it
"""
