[ general ]
  title        = 'Basic SemiXML tests'
  package      = '-'
  module       = '-'
  class        = '-'
  distribution = '-'
  label        = '-'
  date         = '2017-12-26T15:09:12.210466Z'
  oskernel     = 'linux:4.14.4.200.fc.26.x.86._.64'
  osdistro     = 'fedora:26.Workstation.Edition:26:False'
  perl         = 'Perl 6:6.c'
  compiler     = 'rakudo:2017.12.14.gf.137.c.2510'
  vm           = 'moar:2017.12.1.g.912.f.9678'

[ purpose ]
  purposetitle = 'Testing the basic use of SemiXML'
  purpose      = '''
Purpose of this report is that it tests the parsing and translating process of the several parts of the language. Here only the simple structures are tested and not the methods to generate new content. 
'''

[ chapters ]
  list         = [ 'Generate a simple element', 'Add attributes.', 'Nested elements.', 'Element blocks and their different types.' ]

[ chapter.'Generate a simple element' ]
  success      = 2
  fail         = 0
  todo         = 0
  skipped      = 0

[ chapter.'Add attributes.' ]
  success      = 7
  fail         = 1
  todo         = 0
  skipped      = 0

[ chapter.'Nested elements.' ]
  success      = 1
  fail         = 0
  todo         = 0
  skipped      = 0

[ chapter.'Element blocks and their different types.' ]
  success      = 1
  fail         = 0
  todo         = 0
  skipped      = 0

[ summary.line-7 ]
  chapter      = 'Generate a simple element'
  diagnostic   = """
    ok 1 - The object is-a 'SemiXML::Sxml'
"""

[ summary.line-10 ]
  chapter      = 'Generate a simple element'
  diagnostic   = """
    ok 2 - The generated xml is conforming the standard
"""

[ summary.line-13 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 3 - attribute without spaces in value
"""

[ summary.line-17 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 4 - attribute with double quoted value
"""

[ summary.line-21 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 5 - attribute with single quoted value
"""

[ summary.line-25 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 6 - attribute with bracketed <> value
"""

[ summary.line-29 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 7 - attribute a1 found
"""

[ summary.line-30 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 8 - attribute a2 found
"""

[ summary.line-35 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    ok 9 - true boolean attribute a1 found
"""

[ summary.line-36 ]
  chapter      = 'Add attributes.'
  diagnostic   = """
    not ok 10 - false boolean attribute a2 found
    Failed test 'false boolean attribute a2 found'
    at xt/Sxml/basic.t line 36
    expected: '/ 'a2="0"' /'
    got: '<?xml version="1.0" encoding="UTF-8"?>
    <some-element a1="1"/>'
"""

[ summary.line-38 ]
  chapter      = 'Nested elements.'
  diagnostic   = """
    ok 11 - An element within another
"""

[ summary.line-43 ]
  chapter      = 'Element blocks and their different types.'
  diagnostic   = """
    ok 12 - two blocks on an element
"""
