[ general ]
  title        = 'Basic SemiXML tests'
  package      = '-'
  module       = '-'
  class        = '-'
  distribution = '-'
  label        = '-'
  date         = '2017-12-22T19:16:01.508804Z'
  oskernel     = 'linux:4.14.4.200.fc.26.x.86._.64'
  osdistro     = 'fedora:26.Workstation.Edition:26:False'
  perl         = 'Perl 6:6.c'
  compiler     = 'rakudo:2017.12.14.gf.137.c.2510'
  vm           = 'moar:2017.12.1.g.912.f.9678'

[ purpose ]
  purposetitle = 'Testing the basic use of SemiXML'
  purpose      = '''
Purpose of this report is that it tests the parsing and translating process. 
'''

[ chapters ]
  list         = [ 'Generate a simple element', 'jklzflkjhflkja fd', 'Add an attribute. Then add more and play with quotes and type.', 'Nested elements.', 'Elements with more than one block.', 'Elements with different types of blocks.' ]

[ chapter.c1 ]
  name         = 'Generate a simple element'
  success      = 2
  fail         = 1
  todo         = 0
  skipped      = 0

[ chapter.c2 ]
  name         = 'jklzflkjhflkja fd'
  success      = 2
  fail         = 2
  todo         = 1
  skipped      = 0

[ summary.line-7 ]
  chapter      = 'Generate a simple element'
  diagnostic   = """
    ok 1 - The object is-a 'SemiXML::Sxml'
"""

[ summary.line-12 ]
  chapter      = 'Generate a simple element'
  diagnostic   = """
    ok 2 - The generated xml is conforming the standard
"""

[ summary.line-15 ]
  chapter      = 'Generate a simple element'
  diagnostic   = """
    not ok 3 - uhmm...
    Failed test 'uhmm...'
    at xt/Sxml/basic.t line 15
    expected: '3'
    got: '2'
"""

[ summary.line-16 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 4 - jhg djhgasd asjh
    Looks like you planned 7 tests, but ran 4
    Looks like you failed 2 tests of 4
    Failed test 'jhg djhgasd asjh'
    at xt/Sxml/basic.t line 16
"""

[ summary.line-19 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    ok 1 - yes one is one
"""

[ summary.line-20 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    ok 2 - and two is two
"""

[ summary.line-21 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 3 - and two is not three
    Failed test 'and two is not three'
    at xt/Sxml/basic.t line 21
    expected: '3'
    got: '2'
"""

[ summary.line-23 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 4 - return a failure
    Failed test 'right exception type (Str)'
    at /home/marcel/Software/perl6/rakudo/install/share/perl6/precomp/F361351ED957B4147A315862EE8FA5E0886319B7.1513967070.02457/C7/C712FE6969F786C9380D643DF17E85D06868219E line 1
    Expected: Str
    Got:      X::AdHoc
    Exception message: awkward
    Looks like you failed 1 test of 3
    Failed test 'return a failure'
    at xt/Sxml/basic.t line 23
"""

[ summary.line-27 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 5 - jhgj jh jh jhg # TODO working on it
"""

[ summary.line-28 ]
  chapter      = 'jklzflkjhflkja fd'
  diagnostic   = """
    not ok 1 - not yet, maybe later # TODO working on it
"""
