[ C ]
  tracing       = true

#-------------------------------------------------------------------------------
[ ML.html ]
  test          = 'SxmlLib::Testing::Test'
  summary       = 'SxmlLib::Testing::Summary'
#  lorem         = 'SxmlLib::LoremIpsum'

#-------------------------------------------------------------------------------
[ R.html ]
  pdf           = 'wkhtmltopdf - %op/%of.pdf'

#-------------------------------------------------------------------------------
[ S.html ]
  rootpath      = 'xt/Sxml/Reports'

#-------------------------------------------------------------------------------
# Tracing tables
[ T ]
#  config        = true
#  tables        = true
  modules       = true
#  parse         = true
#  parse-result  = true
  file-handling = true
