[ C ]
  tracing       = true

#-------------------------------------------------------------------------------
[ ML.html ]
  test          = 'SxmlLib::Testing::Test'
  summary       = 'SxmlLib::Testing::Summary'
  css           = 'SxmlLib::Css'
#  lorem         = 'SxmlLib::LoremIpsum'

#-------------------------------------------------------------------------------
[ R ]
  cat           = 'cat > "%op/Xml/%of.%oe"'

[ R.html ]
  pdf           = 'wkhtmltopdf - %op/%of.pdf'

#-------------------------------------------------------------------------------
#[ S.html ]
[ S ]
  rootpath      = 'xt/Sxml/Reports'

#-------------------------------------------------------------------------------
# Tracing tables
[ T ]
  config        = true
  tables        = true
  modules       = true
#  parse         = true
#  parse-result  = true
  file-handling = true
