[ C ]
  tracing       = false

#------------------------------------------------------------------------------
[ ML ]
  test          = 'SxmlLib::Testing::Test'
  summary       = 'SxmlLib::Testing::Summary'
#  lorem         = 'SxmlLib::LoremIpsum'

#------------------------------------------------------------------------------
[ R.html ]
  pdf           = 'wkhtmltopdf - %op/%of.pdf'

#------------------------------------------------------------------------------
# Tracing tables
[ T ]
#  config        = true
#  tables        = true
#  modules       = true
#  parse         = true
#  parse-result  = true
  file-handling = true
