# Special settings when generating reports using TestDoc module
#
[option.doctype]
  show          = 0

[output]
  fileext       = 'html'

[output.program]
  xpdf           = 'wkhtmltopdf - x.pdf'
  pdf           = 'wkhtmltopdf - %of.pdf'

  fileext       = 'pdf'

[module]
  td            = 'SxmlLib::Testing::TestDoc'
