[option.doctype]
  show          = 0

[output]
  fileext       = 'html'

[output.program]
  pdf           = 'wkhtmltopdf - %of.pdf'
  fmt           = 'xmllint --format - > %of.%oe'
  chk           = 'tee sxml2xml.xml | xmllint --format - | rnv /usr/share/xml/docbook5/schema/rng/5.0/docbook.rnc'

[module]
  report        = 'SxmlLib::Testing::Report'
  code          = 'SxmlLib::Testing::Code'
  test          = 'SxmlLib::Testing::Test'
  todo          = 'SxmlLib::Testing::Todo'
  bug           = 'SxmlLib::Testing::Bug'
  skip          = 'SxmlLib::Testing::Skip'
  lorem         = 'SxmlLib::LoremIpsum'
