[ C ]
  tracing       = true

#------------------------------------------------------------------------------
[ R.html ]
  pdf           = 'wkhtmltopdf - %op/%of.pdf'

#------------------------------------------------------------------------------
# Tracing tables
[ T ]
#  config        = true
#  tables        = true
  modules       = true
#  parse         = true
#  parse-result  = true
  file-handling = true
