#------------------------------------------------------------------------------
[ C ]
  xml-show      = true
  doctype-show  = true
  tracing       = true

#------------------------------------------------------------------------------
[ D.Db5 ]
  pdf           = [ 'xml;xsl;ss-fo.sxml']
  chunk         = [ 'xml;xsl;ss-chunk.sxml']
  xhtml         = [ 'xml;xsl;ss-xhtml.sxml']

#------------------------------------------------------------------------------
[ E.Db5.Manual ]
  pack          = 'SemiXML'
  mod           = 'SemiXML::Sxml'
  act           = 'SemiXML::Actions'
  gram          = 'SemiXML::Grammar'
  lib           = 'SxmlLib'
  prog          = 'sxml2xml'
  lang          = 'sxml'
  nbsp          = ' '
  copy          = '&#xa9;'
  E             = 'element'

#------------------------------------------------------------------------------
[ ML.Db5 ]
  lorem         = 'SxmlLib::LoremIpsum'
  Db5b          = 'SxmlLib::Docbook5::Basic'
  Db5f          = 'SxmlLib::Docbook5::FixedLayout'

#------------------------------------------------------------------------------
[ R.xml ]
  xml           = 'xmllint --format - > %op/%of.%oe'
  xsl           = [ 'xmllint --format - > %op/%of.%oe', '%op/%of.%oe']

[ R.Db5 ]
  pdf           = [
   'xsltproc --encoding utf-8 %op/Xsl/ss-fo.xsl - | xep -fo - -pdf %op/%of.%oe',
   '%op/%of.%oe'
  ]

  xhtml         = 'xsltproc --encoding utf-8 --xinclude %op/Xsl/ss-xhtml.xsl - > %op/%of.%oe'
  chunk         = 'xsltproc --encoding utf-8 %op/Xsl/ss-chunk.xsl -'

  xml           = 'xmllint --format - > %op/%of.%oe'

  # Generate formatted xml first and save it on disk (tee command)
  # then send formatted xml to rnc for checking. This way the errors
  # can be found at the proper line in the saved xml file.
  check         = 'xmllint --format - | tee %op/%of.%oe |rnv /usr/share/xml/docbook5/schema/rng/5.0/docbook.rnc'

#------------------------------------------------------------------------------
# Default name of the file
[ S ]
#  filename      = 'Manual'
  rootpath      = 'doc/Manual'

[ S.pdf ]
  fileext       = 'pdf'

[ S.xml ]
  fileext       = 'xml'
  filepath      = 'Xml'

[ S.check ]
  fileext       = 'xml'
  filepath      = 'Xml'

[ S.xsl ]
  fileext       = 'xsl'
  filepath      = 'Xsl'

[ S.xhtml ]
  fileext       = 'xhtml'

#------------------------------------------------------------------------------
[ T ]
#  config-search = false
  config        = false
  tables        = false
  modules       = true
  parse         = true
  parse-result  = false
  file-handling = true
