#------------------------------------------------------------------------------
[ C ]
  xml-show      = true
  doctype-show  = true
  tracing       = true

#------------------------------------------------------------------------------
[ D.db5 ]
  pdf           = 'xml; xsl; ss-fo.sxml'
  chunk         = [ 'xml;xsl;ss-chunk.sxml']
  xhtml         = [ 'xml;xsl;ss-xhtml.sxml']

#------------------------------------------------------------------------------
[ E.db5.Manual ]
  pack          = '<emphasis>SemiXML</emphasis>'
  mainmod       = '<emphasis>SemiXML::Sxml</emphasis>'
  #act           = 'SemiXML::Actions'
  #gram          = 'SemiXML::Grammar'
  #lib1          = 'SemiXML'
  #lib2          = 'SxmlLib'
  prog1         = '<emphasis>sxml2xml</emphasis>'
  prog2         = '<emphasis>xml2sxml</emphasis>'
  fileext       = '<emphasis>.sxml</emphasis>'
  lang          = '<emphasis>semi-xml</emphasis>'
  nbsp          = ' '
  copy          = '&#xa9;'
  #E             = 'element'
  #exclam        = '&#33;'

#------------------------------------------------------------------------------
[ ML.db5 ]
  lorem         = 'SxmlLib::LoremIpsum'
  db5           = 'SxmlLib::Docbook5::Basic'
  #db5f          = 'SxmlLib::Docbook5::FixedLayout'

#------------------------------------------------------------------------------
[ R.xml ]
  xml           = 'xmllint --format - > %op/%of.%oe'
  xsl           = [ 'xmllint --format - > %op/%of.%oe', '%op/%of.%oe']

[ R.db5 ]
  pdf           = [
   'xsltproc --encoding utf-8 %op/Xsl/ss-fo.xsl - | xep -fo - -pdf %op/%of.%oe',
   '%op/%of.%oe'
  ]

  xhtml         = 'xsltproc --encoding utf-8 --xinclude %op/Xsl/ss-xhtml.xsl - > %op/%of.%oe'
  chunk         = 'xsltproc --encoding utf-8 %op/Xsl/ss-chunk.xsl -'

  xml           = 'xmllint --format - > %op/%of.%oe'

  # Generate formatted xml first and save it on disk (tee command)
  # then send formatted xml to rnc for checking. This way the errors
  # can be found at the proper line in the saved xml file.
  check         = 'xmllint --format - | tee %op/%of.%oe |rnv /usr/share/xml/docbook5/schema/rng/5.0/docbook.rnc'

#------------------------------------------------------------------------------
# Default name of the file
[ S ]
#  filename      = 'Manual'
  rootpath      = 'doc/Manual'

[ S.xml ]
  filepath      = 'Xml'

[ S.check ]
  filepath      = 'Xml'

[ S.xsl ]
  filepath      = 'Xsl'

#------------------------------------------------------------------------------
[ T ]
#  config-search = false
  config        = true
#  tables        = true
  modules       = true
  parse         = false
  parse-result  = false
  file-handling = true
